services:
  mysql:
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "\"\"", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: laravel_mail
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
